compressionLevel: mixed

enableGlobalCache: true

logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard

nodeLinker: node-modules

packageExtensions:
  "@nextui-org/react@*":
    peerDependencies:
      tailwindcss: "*"
  "@nextui-org/system@*":
    peerDependencies:
      "@nextui-org/theme": "*"
  "@nextui-org/theme@*":
    peerDependencies:
      tailwindcss: "*"
  focus-trap-react@*:
    peerDependencies:
      prop-types: "*"
  resend@*:
    peerDependencies:
      react: "*"
      react-dom: "*"

yarnPath: .yarn/releases/yarn-4.6.0.cjs
